这几天一直在写论文，都没有时间看点技术文章写日志了
#try\catch\finally
```javascript
// 当try中触发异常的时候，如果本层有catch，执行catch，然后执行finally。
// 如果本层没有catch，就先执行finally，然后向上抛出异常
// catch(e){}中的e就是throw的东西。即如果throw "hello world"，那么e就是'hello world'

(function (){
    try {
        (function() {
            try {
                throw "hello world"
            } finally {
                console.info('inner finally');
            }
        })();
    } catch (e) {
        console.info('catch outter');
    } finally {
        console.info('finally outter');
    }
})();

// inner finally
// catch outter
// finally outter
```

